### ISSUE TITLE
Question about file uploads

### ISSUE THREAD

**Issue by mhavard999** [Pylons/pyramid_cookbook#126]
I'm not sure if this is the right place to post this, but I am confused about a snippet from [file_uploads.rst](https://github.com/Pylons/pyramid_cookbook/blob/master/forms/file_uploads.rst):

```python
    file_path = os.path.join('/tmp', '%s.mp3' % uuid.uuid4())

    # We first write to a temporary file to prevent incomplete files from
    # being used.

    temp_file_path = file_path + '~'
    output_file = open(temp_file_path, 'wb')

    # Finally write the data to a temporary file
    input_file.seek(0)
    while True:
        data = input_file.read(2<<16)
        if not data:
            break
        output_file.write(data)

    # If your data is really critical you may want to force it to disk first
    # using output_file.flush(); os.fsync(output_file.fileno())

    output_file.close()

    # Now that we know the file has been fully saved to disk move it into place.

    os.rename(temp_file_path, file_path)
```

First of all, I am not sure how this protects against saving incomplete files.  If I make this change:
```python
    breakLoop = False
    while True:
        data = input_file.read(2<<16)
        if not data or breakLoop:
            break
        output_file.write(data)
        breakLoop = True
```
and say the file is bigger than 2<<16 bytes, it will still proceed on to the next chunk of code as it normally would, and it saves the incomplete file as `file_path`.  From the explanation in the rest of the document as well as the comments in the code, it would seem that this code is supposed to prevent that from happening.

And then another question - why are you doing this in a loop instead of just `output_file.write(input_file.read())`?

I'm sure I'm missing something here, and any help would be much appreciated.  Thanks!

**Comment by mmerickel** [comment]
`input_file.read()` would load the entire file into memory which is definitely not what you want. You could use something like `shutil.copyfileobj(input_file, output_file)`. It's standard practice to read the data in chunks.

**Comment by stevepiercy** [comment]
@mhavard999 if @mmerickel's response answers your question, then please close this issue. Thank you!

**Comment by mmerickel** [comment]
If you wanted to update the example to something like the following, I'd be happy to merge that PR.

```python
file_path = os.path.join('/tmp', '%s.mp3' % uuid.uuid4())
temp_file_path = file_path + '~'

input_fp = request.POST['mp3'].file
with open(temp_file, 'wb') as output_fp:
    shutil.copyfileobj(input_fp, output_fp)

os.rename(temp_file_path, file_path)
```
