### ISSUE TITLE
Rename to "Pyramid Community Cookbook"

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid_cookbook#155]
People continue to misinterpret the Pyramid Cookbook as "official" documentation, not community contributed. Renaming it to "Pyramid Community Cookbook" would be one step toward reducing that common misinterpretation. I do not suggest changing the URL or repo, just its name. (A new Sphinx theme would also help, but this is a quick fix.)

Please provide your opinion.

**Comment by pauleveritt** [comment]
Very, very good idea.

**Comment by mmerickel** [comment]
+1, do it! This is definitely a better title.

**Comment by stevepiercy** [comment]
Closed by https://github.com/Pylons/pyramid/pull/2234, https://github.com/Pylons/pyramid/pull/2235, and https://github.com/Pylons/pyramid/pull/2236
