### ISSUE TITLE
Remove Basic Authentication Policy

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid_cookbook#167]
Is this recipe obsolete?

Basic Authentication Policy
http://docs.pylonsproject.org/projects/pyramid-cookbook/en/latest/auth/basic.html

paste was removed from Pyramid in v1.3:
http://docs.pylonsproject.org/projects/pyramid/en/latest/api/authentication.html#pyramid.authentication.BasicAuthAuthenticationPolicy

Also it looks like it was replaced in 1.4a3 by this:
http://docs.pylonsproject.org/projects/pyramid/en/latest/changes.html#id37

If a Pyramid historian can verify that finding, I'll remove the cookbook recipe.

**Comment by mmerickel** [comment]
I'm fine with removing the policy from the cookbook but it would be nice if we did a better job somewhere of explaining how to use the policy. The cookbook recipe is a little bit more full-featured than the low-level api docs unfortunately.

**Comment by stevepiercy** [comment]
How about flagging it for an update and modernization instead of deletion? In the meanwhile, I can put a disclaimer of its status.

**Comment by mmerickel** [comment]
If you want. The most difficult part of a community cookbook is actually keeping things up to date! Also the example works, even if it's not the best way to do it now.

**Comment by vog** [comment]
HTTP Basic Auth is not yet integrated seamlessly into Pyramid. For example you need to adjust the `forbidden_view`, using BasicAuthAuthenticationPolicy alone is not sufficient. See also https://github.com/Pylons/pyramid/issues/3066 for the latest discussion on that topic.

Moreover, I personally found that receipe quite helpful. See also #183, #185 and #186 for some cleanup.

And even then, if the HTTP Basic Auth integration was 100% seamless in Pyramid, I would still prefer to have that simple receipe here, as the BasicAuthAuthenticationPolicy is a bit hidden in that comprehensive Pyramid docs.

**Comment by mmerickel** [comment]
I wrote a full example for someone in IRC the other day. https://gist.github.com/mmerickel/e530f16dae61cf2960d301c7c01309b0

Something like it probably belongs in either Pyramid's core docs or in the cookbook if someone wants to work on that. It looks like https://github.com/Pylons/pyramid/pull/3079 also helps with this a lot.

**Comment by stevepiercy** [comment]
Closed by #183, #185, #186, and #187
