### ISSUE TITLE
Usage of wsgiapp2 over wsgiapp in porting/wsgi

### ISSUE THREAD

**Issue by jkmartindale** [Pylons/pyramid_cookbook#203]
What's the reason for using **wsgiapp2** over **wsgiapp** in the WSGI porting example?

I found usage of **wsgiapp2** a bit confusing, because it wasn't obvious to me that a route that was formerly at `http://host/++namespace++/index.html` would become `http://host/[literallyanything]/++namespace++/index.html`, whereas using **wsgiapp** it would remain the same as before. From how I see it, **wsgiapp** would be more useful than **wsgiapp2** for porting an arbitrary WSGI app.

But to be fair, I'm trying to port Zope namespace traversal to Pyramid with very little knowledge of either, so maybe I'm just missing something.

**Comment by stevepiercy** [comment]
I would suggest that you ask your question in a forum with a much larger audience, specifically https://groups.google.com/forum/#!forum/pylons-discuss or https://stackoverflow.com/questions/tagged/pyramid per https://pylonsproject.org/community-support.html

That said, perhaps there is more guidance in https://docs.pylonsproject.org/projects/pyramid/en/latest/api/wsgi.html

**Comment by stevepiercy** [comment]
It's been two months since this question was asked with no further discussion. I'm closing it as a stale issue.
