### ISSUE TITLE
Updates for Gunicorn 20

### ISSUE THREAD

**Issue by tilgovi** [Pylons/pyramid_cookbook#222]
In versions of Gunicorn prior to 20, use of `egg:gunicorn#main` was
deprecated when used with external script runners and the Gunicorn
documentation suggested use of the Gunicorn CLI directly.

As requests came into the Gunicorn issue tracker for the ability to advanced
Paste features like specifying globals for interpolation in the config
file and using alternate `server` blocks, it became clear that adding
these features would significantly inflate the surface of the Gunicorn
CLI. Furthermore, it was potentially confusing that using
the Gunicorn CLI while specifying another server in the `server` block
would still use Gunicorn as the server.

For version 20, it was decided that it is best to let the tools of the
Paste ecosystem manage invoking the server. It is no longer deprecated
to specify `egg:gunicorn#main` as the server and invoke Gunicorn with
`pserve`. Gunicorn is fully supported as a Paste Deploy server factory.
Additionally, the Gunicorn CLI fully supports reading a Paste Deploy app
factory from a `.ini` file. However, Gunicorn is _not_ a Paste Script runner.

I suggest removing the "short story" from the gunicorn.rst. It is better to
suggest that users change their `.ini` server block to use Gunicorn but to
keep the invocation of `pserve` as before.

**Comment by tilgovi** [comment]
More information here: http://docs.gunicorn.org/en/stable/run.html#paste-deployment

**Comment by stevepiercy** [comment]
I'd accept a PR with the changes. This is, after all, the Pyramid _Community_ Cookbook. :wink:

**Comment by tilgovi** [comment]
@stevepiercy understood! I almost started with that, but backed away because I couldn't decide exactly what to do. But I guess there's no one better to decide than myself :). PR incoming.

**Comment by tilgovi** [comment]
PR at #223.
