### ISSUE TITLE
AWS via Elastic Beanstalk links are broken

### ISSUE THREAD

**Issue by bhavika** [Pylons/pyramid_cookbook#228]
Both tutorials mentioned [here](https://docs.pylonsproject.org/projects/pyramid-cookbook/en/latest/deployment/aws_via_eb.html) seem to no longer exist.

**Comment by stevepiercy** [comment]
Thanks for the report. Would you please submit a PR with the [Internet Archive](https://archive.org/) links? That's what we do when third parties remove posts.
